#!/usr/bin/env python3
"""Make the site's responsive images from the originals in _assets-src/.

Usage (from the repo root):
    .venv/bin/python scripts/optimize_images.py [--force] [NAME ...]

Reads _assets-src/images.yml, which lists every output image (its name under
assets/img/, its original, and the sizes to make), and writes:

    assets/img/<name>-<size>.<format>   one file per size and format
    _data/images.yml                    sizes and formats, for the
                                        responsive-image include

Photos get AVIF, WebP, and a JPEG fallback; images with transparency (logos)
get WebP and a PNG fallback. Colors are converted to sRGB and metadata (EXIF,
including GPS positions) is dropped. Outputs newer than their original are
kept unless --force is given; NAME limits the run to those entries.
Requires Pillow (with AVIF support) and PyYAML, both in .venv.
"""

import argparse
import io
import sys
from pathlib import Path

import yaml
from PIL import Image, ImageCms, ImageOps

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ROOT / "_assets-src"
CONFIG = SOURCES / "images.yml"
OUTPUT = ROOT / "assets" / "img"
MANIFEST = ROOT / "_data" / "images.yml"

DEFAULT_FORMATS = ["avif", "webp", "jpg"]
SAVE_OPTIONS = {
    "avif": {"format": "AVIF", "quality": 60, "speed": 4},
    "webp": {"format": "WEBP", "quality": 80, "method": 6},
    "jpg": {"format": "JPEG", "quality": 82, "optimize": True, "progressive": True},
    "png": {"format": "PNG", "optimize": True},
}
HEADER = """\
# Generated by scripts/optimize_images.py from _assets-src/images.yml; do not
# edit. The responsive-image include reads it: for each image, the formats
# (the last one is the <img> fallback), the srcset descriptor (w for widths,
# x for 1x/2x/3x), the fallback size, and every size with its pixel dimensions.
"""


def to_srgb(image: Image.Image) -> Image.Image:
    """Convert an image with an embedded color profile (such as Display P3) to sRGB."""
    icc = image.info.get("icc_profile")
    if not icc:
        return image
    source = ImageCms.ImageCmsProfile(io.BytesIO(icc))
    target = ImageCms.createProfile("sRGB")
    mode = "RGBA" if "A" in image.getbands() else "RGB"
    return ImageCms.profileToProfile(image, source, target, outputMode=mode)


def load(entry: dict) -> Image.Image:
    image = Image.open(SOURCES / entry["src"])
    image = ImageOps.exif_transpose(image)
    image = to_srgb(image)
    keep_alpha = "png" in entry.get("formats", DEFAULT_FORMATS)
    image = image.convert("RGBA" if keep_alpha else "RGB")
    if entry.get("trim"):
        box = image.getbbox()
        if box:
            image = image.crop(box)
    if entry.get("crop") == "square":
        side = min(image.size)
        left, top = (image.width - side) // 2, (image.height - side) // 2
        image = image.crop((left, top, left + side, top + side))
    return image


def plan(entry: dict, image: Image.Image) -> list[dict]:
    """Return the sizes to make: size label, pixel width and height, density."""
    variants = []
    if "heights" in entry:
        base = entry["heights"][0]
        for height in entry["heights"]:
            width = round(image.width * height / image.height)
            variants.append({"size": height, "w": width, "h": height, "x": height / base})
    else:
        for width in entry["widths"]:
            if width > image.width:
                sys.exit(f"{entry['src']}: {width} px is wider than the original ({image.width} px)")
            height = round(image.height * width / image.width)
            variants.append({"size": width, "w": width, "h": height})
    return variants


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("names", nargs="*", help="only these entries (default: all)")
    parser.add_argument("--force", action="store_true", help="rewrite outputs even if they are up to date")
    args = parser.parse_args()

    config = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    unknown = set(args.names) - set(config)
    if unknown:
        sys.exit(f"not in {CONFIG.relative_to(ROOT)}: {', '.join(sorted(unknown))}")

    manifest = {}
    for name, entry in config.items():
        formats = entry.get("formats", DEFAULT_FORMATS)
        source = SOURCES / entry["src"]
        image = load(entry)
        variants = plan(entry, image)
        if entry["fallback"] not in [v["size"] for v in variants]:
            sys.exit(f"{name}: fallback {entry['fallback']} is not one of its sizes")
        descriptor = "x" if "heights" in entry else "w"
        manifest[name] = {
            "formats": list(formats),  # a copy, so the YAML output has no anchors
            "descriptor": descriptor,
            "fallback": entry["fallback"],
            "variants": [
                {k: (int(v) if k == "x" and float(v).is_integer() else v) for k, v in variant.items()}
                for variant in variants
            ],
        }
        if args.names and name not in args.names:
            continue

        written = 0
        for variant in variants:
            resized = None
            for fmt in formats:
                target = OUTPUT / f"{name}-{variant['size']}.{fmt}"
                if not args.force and target.exists() and target.stat().st_mtime >= source.stat().st_mtime:
                    continue
                if resized is None:
                    resized = image.resize((variant["w"], variant["h"]), Image.Resampling.LANCZOS)
                target.parent.mkdir(parents=True, exist_ok=True)
                options = dict(SAVE_OPTIONS[fmt])
                if "quality" in entry and "quality" in options:
                    options["quality"] = entry["quality"]
                resized.save(target, **options)
                written += 1
        sizes = ", ".join(f"{v['w']}x{v['h']}" for v in variants)
        print(f"{name:34} {len(variants) * len(formats):2} files ({written} written)  {sizes}")

    MANIFEST.write_text(HEADER + "\n" + yaml.safe_dump(manifest, sort_keys=False, default_flow_style=None, width=100), encoding="utf-8")
    print(f"wrote {MANIFEST.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
